name: CI Next.js com Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  general-tests:
    name: Testes Gerais (sem Mongo)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Rodar Testes sem integração
        run: npm test -- --testPathIgnorePatterns=app/__tests__/integration/split.test.ts

  integration-tests:
    name: Testes de Integração com MongoDB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    # Só no Linux usa container
    services:
      mongo:
        if: matrix.os == 'ubuntu-latest'
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      # Instala manualmente o MongoDB apenas no Windows e macOS
      - name: Instalar MongoDB no macOS
        if: runner.os == 'macOS'
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb/brew/mongodb-community

      - name: Instalar MongoDB no Windows
        if: runner.os == 'Windows'
        run: |
          choco install mongodb --version=6.0.13 --params="/InstallDir:C:\mongodb"
          mkdir C:\data\db
          Start-Process -FilePath "C:\mongodb\bin\mongod.exe" -ArgumentList "--dbpath=C:\data\db" -NoNewWindow

      - name: Esperar MongoDB subir
        run: sleep 15

      - name: Rodar Testes de Integração
        run: npm test app/__tests__/integration/split.test.ts
        env:
          MONGODB_URI: mongodb://localhost:27017/testdb
