name: CI Next.js com Jest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # Testes unitários que não precisam de MongoDB
  general-tests:
    name: Testes Gerais (sem Mongo)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Rodar Testes sem integração
        run: npm test -- --testPathIgnorePatterns=app/__tests__/integration/split.test.ts

  # Testes de integração com MongoDB em todos os SOs (instala manualmente o Mongo)
  integration-tests:
    name: Testes de Integração com MongoDB
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci

      - name: Instalar MongoDB no Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg curl
          curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg -o /usr/share/keyrings/mongodb-server-6.0.gpg --dearmor
          echo "deb [ signed-by=/usr/share/keyrings/mongodb-server-6.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod

      - name: Instalar MongoDB no macOS
        if: runner.os == 'macOS'
        run: |
          brew tap mongodb/brew
          brew install mongodb-community@6.0
          brew services start mongodb/brew/mongodb-community

      - name: Instalar MongoDB no Windows
        if: runner.os == 'Windows'
        run: |
          choco install mongodb --version=6.0.13 --params="/InstallDir:C:\mongodb"
          mkdir C:\data\db
          Start-Process -FilePath "C:\mongodb\bin\mongod.exe" -ArgumentList "--dbpath=C:\data\db" -NoNewWindow

      - name: Esperar MongoDB subir
        run: sleep 15

      - name: Rodar Testes de Integração
        run: npm test app/__tests__/integration/split.test.ts
        env:
          MONGODB_URI: mongodb://localhost:27017/testdb
